use_frameworks!
def shared_pods
    pod 'SkyFloatingLabelTextField', '~> 2.0.0'
    pod 'MBCircularProgressBar'
    pod 'UPCarouselFlowLayout'
    pod 'BWWalkthrough'


end

target 'scrum-ios' do
	platform :ios, '8.2'
	shared_pods
end
